name: jsDelivr

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 10 * * *'

jobs:
  jsdelivr:
    name: jsDelivr
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install PNPM
        run: npm i pnpm -g

      - name: Run setup
        run: npm run setup

      - name: Run cache purge
        run: npm run cache:purge
